name: iaido_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  collection: ^1.18.0
  drift: ^2.16.0
  flutter:
    sdk: flutter
  flutter_sticky_header: ^0.6.5
  get: ^4.6.6
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.2
  sqlite3: ^2.4.0
  sqlite3_flutter_libs: ^0.5.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  drift_dev: ^2.16.0
  mocktail: ^1.0.3
  test: ^1.24.9

flutter:
  uses-material-design: true
